# generated by datamodel-codegen:
#   filename:  lesson_output_schema.json
#   timestamp: 2025-12-28T19:42:11+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel, field_validator

from backend.lesson_schema_enums import FrameType, ModelName, PatternId, ProficiencyLevel


class Metadata(BaseModel):
    week_of: str = Field(
        ...,
        description="Week date range (MM/DD-MM/DD)",
        examples=["10/6-10/10", "3/15-3/19"],
        pattern="^\\d{1,2}/\\d{1,2}-\\d{1,2}/\\d{1,2}$",
    )
    grade: str = Field(
        ..., description="Grade level", examples=["K", "1", "2", "7", "12"]
    )
    subject: str = Field(
        ...,
        description="Subject area",
        examples=["Social Studies", "Math", "Language Arts", "Science"],
    )
    homeroom: str = Field(
        ...,
        description="Homeroom or class identifier",
        examples=["302", "Room 15", "Class A"],
    )
    room: str | None = Field(
        None,
        description="Room number or physical location where instruction takes place",
        examples=["215", "302", "Science Lab A", "Building B, Room 15"],
    )
    teacher_name: str = Field(..., description="Primary teacher name")


class Objective(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    content_objective: str = Field(
        ...,
        description="Original content objective from primary teacher",
        examples=[
            "Students will be able to explain how systems of law and banking enabled growth in trade, wealth, and peace"
        ],
        min_length=10,
    )
    student_goal: str = Field(
        ...,
        description="Student-friendly 'I will...' version (max 12 words for board posting) that explicitly names the WIDA language domains (listening, reading, speaking, writing) students will practice and ends with a parentheses domain tag followed by a period (e.g., '(listening, speaking).')",
        examples=[
            "I will explain Roman systems using evidence and speak with my team (speaking).",
            "I will read the article, discuss it, and write a summary (reading, speaking, writing).",
        ],
        max_length=120,
        min_length=5,
        pattern="^(?=.*\\b(?:[Ll]isten(?:ing)?|[Rr]ead(?:ing)?|[Ss]peak(?:ing)?|[Ww]rit(?:e|ing))\\b).*\\((?: *(?:listening|reading|speaking|writing))(?: *, *(?:listening|reading|speaking|writing))* *\\)\\.$",
    )
    wida_objective: str = Field(
        ...,
        description="Complete WIDA bilingual language objective with ELD standard",
        examples=[
            "Students will use language to explain how Roman law, banking, and Pax Romana enabled economic growth (ELD-SS.6-8.Explain.Reading/Writing) by using cognate awareness and graphic organizers with Portuguese-English vocabulary bridges appropriate for WIDA levels 2-5, producing a written explanation that demonstrates understanding of cause-effect relationships in historical systems."
        ],
        min_length=50,
        pattern=".*ELD-[A-Z]{2}\\.[0-9K-]+\\.[A-Za-z]+\\.(?:Listening|Reading|Speaking|Writing)(?:/(?:Listening|Reading|Speaking|Writing))*.*",
    )


class AnticipatorySet(BaseModel):
    original_content: str = Field(
        ...,
        description="Original anticipatory set from primary teacher",
        examples=["Students will respond to an everybody writes."],
    )
    bilingual_bridge: str = Field(
        ...,
        description="1-2 concrete steps to connect L1/culture to lesson entry",
        examples=[
            "Preview key Portuguese-English vocabulary pairs: **law** → *lei*, **banking** → *banco*, **trade** → *comércio*, **peace** → *paz*. Quick L1 connection: 'Como as leis ajudam o comércio?' (How do laws help trade?)"
        ],
        min_length=20,
    )


class SpecialNeedsSupportItem(RootModel[str]):
    root: str = Field(
        ...,
        examples=[
            "Visual timeline of Roman systems; color-code law (blue), banking (green), Pax Romana (gold)"
        ],
        min_length=10,
    )


class Material(RootModel[str]):
    root: str = Field(
        ...,
        examples=[
            "Bilingual vocabulary chart (poster paper)",
            "Cornell Notes template (handout)",
            "Sentence frame strips",
        ],
        min_length=5,
    )


class ImplementationNote(RootModel[str]):
    root: str = Field(
        ...,
        examples=["Prepare 3 station signs, rotation chart, visual timer"],
        min_length=10,
    )


class Phase(BaseModel):
    phase_name: str = Field(
        ...,
        description="Phase name (Warmup, Input, Practice, Closure, etc.)",
        examples=["Warmup", "Practice", "Closure", "Input"],
        min_length=3,
    )
    minutes: int = Field(..., description="Duration in minutes", ge=1, le=45)
    bilingual_teacher_role: str = Field(
        ...,
        description="Bilingual teacher's role during this phase",
        examples=["Station 1: Intensive vocabulary/L1 cognate work with Levels 2-3"],
        min_length=10,
    )
    primary_teacher_role: str = Field(
        ...,
        description="Primary teacher's role during this phase",
        examples=["Station 2: Content application with Levels 4-5"],
        min_length=10,
    )
    details: str = Field(
        "",
        description="Additional phase details (optional)",
        examples=[
            "Station 3 (Independent): Bilingual materials practice (all levels rotate). Rotation: 10 minutes per station with visual timer"
        ],
    )


class EllStrategy(BaseModel):
    strategy_id: str = Field(
        ...,
        description="Strategy identifier from strategy pack",
        examples=["cognate_awareness", "graphic_organizers", "sentence_frames"],
        pattern="^[a-z_]+$",
    )
    strategy_name: str = Field(
        ...,
        description="Human-readable strategy name",
        examples=["Cognate Awareness", "Graphic Organizers", "Sentence Frames"],
        min_length=5,
    )
    implementation: str = Field(
        ...,
        description="Specific implementation steps for this lesson",
        examples=[
            "Create bilingual vocabulary anchor chart with Portuguese-English pairs: **law** → *lei*, **system** → *sistema*, **economy** → *economia*, **empire** → *império*. Post visibly during slideshow."
        ],
        min_length=30,
    )
    proficiency_levels: str = Field(
        ...,
        description="Target WIDA proficiency levels",
        examples=["Levels 2-5", "Levels 2-3", "Level 1", "Levels 3-4"],
        pattern="^Levels? [0-9](-[0-9])?(, [0-9](-[0-9])?)*$",
    )


class LinguisticNote(BaseModel):
    pattern_id: PatternId = Field(
        ..., description="Pattern identifier from portuguese_misconceptions.json"
    )
    note: str = Field(
        ...,
        description="Explanation of L1→L2 interference",
        examples=[
            "Portuguese speakers often drop subject pronouns ('Go to school' instead of 'I go to school') because verb conjugation shows the person"
        ],
        min_length=30,
    )
    prevention_tip: str = Field(
        ...,
        description="Actionable prevention strategy",
        examples=[
            "Use sentence frames that explicitly include subject pronouns: 'I [verb]...', 'She [verb]...', 'They [verb]...'"
        ],
        min_length=20,
    )


class SupportsByLevel(BaseModel):
    levels_1_2: str = Field(
        ...,
        description="Supports for WIDA Levels 1-2 (Entering/Emerging)",
        examples=[
            "Sentence frame provided, word bank with vocabulary pairs (**law** → *lei*, **system** → *sistema*), allow L1 draft then translate"
        ],
        min_length=20,
    )
    levels_3_4: str = Field(
        ...,
        description="Supports for WIDA Levels 3-4 (Developing/Expanding)",
        examples=[
            "Sentence starter provided, vocabulary pair chart reference (**law** → *lei*, **system** → *sistema*), bilingual dictionary allowed"
        ],
        min_length=20,
    )
    levels_5_6: str = Field(
        ...,
        description="Supports for WIDA Levels 5-6 (Bridging/Reaching)",
        examples=[
            "Open response, optional sentence frames, focus on academic vocabulary"
        ],
        min_length=20,
    )


class BilingualOverlay(BaseModel):
    instrument: str = Field(
        ...,
        description="Assessment instrument type and format",
        examples=[
            "Written exit ticket (1-2 sentences)",
            "Oral presentation (3-5 minutes)",
            "Multiple choice quiz (10 questions)",
        ],
        min_length=10,
    )
    wida_mapping: str = Field(
        ...,
        description="Key Language Use + ELD domain + proficiency levels",
        examples=["Explain + ELD-SS.6-8.Writing + Levels 2-5"],
        pattern=".*(Explain|Narrate|Inform|Argue).*ELD.*Level",
    )
    supports_by_level: SupportsByLevel = Field(
        ..., description="Level-banded supports using only available materials"
    )
    scoring_lens: str = Field(
        ...,
        description="Language-focused scoring criteria aligned to primary rubric",
        examples=[
            "Accept responses showing understanding of cause-effect relationship; credit use of academic vocabulary (**law** → *lei*, **banking** → *banco*, **peace** → *paz*); allow code-switching if meaning is clear"
        ],
        min_length=30,
    )
    constraints_honored: str = Field(
        ...,
        description="Confirmation that no new materials or task changes introduced",
        examples=["No new materials; uses existing exit ticket format"],
        min_length=15,
    )


class VocabularyCognate(BaseModel):
    english: str = Field(..., description="English word", min_length=2)
    portuguese: str = Field(..., description="Portuguese word", min_length=2)
    is_cognate: bool | None = Field(
        ..., description="Whether this is a true cognate pair (optional, can be null)"
    )
    relevance_note: str | None = Field(
        ...,
        description="Brief note on why this word pair is relevant to the lesson (optional, can be null)",
    )


class VocabularyCognates(RootModel[list[VocabularyCognate]]):
    root: list[VocabularyCognate] = Field(
        ...,
        description="List of exactly 6 English-Portuguese word pairs highly relevant to lesson objectives",
        examples=[
            [
                {
                    "english": "law",
                    "portuguese": "lei",
                    "is_cognate": False,
                    "relevance_note": "Core concept for understanding Roman legal systems",
                },
                {
                    "english": "system",
                    "portuguese": "sistema",
                    "is_cognate": True,
                    "relevance_note": "Essential for describing how Roman institutions worked",
                },
                {
                    "english": "banking",
                    "portuguese": "banco",
                    "is_cognate": False,
                    "relevance_note": "Key economic institution enabling trade growth",
                },
                {
                    "english": "economy",
                    "portuguese": "economia",
                    "is_cognate": True,
                    "relevance_note": "Central to understanding economic growth concepts",
                },
                {
                    "english": "trade",
                    "portuguese": "comércio",
                    "is_cognate": False,
                    "relevance_note": "Fundamental concept for lesson on economic systems",
                },
                {
                    "english": "peace",
                    "portuguese": "paz",
                    "is_cognate": False,
                    "relevance_note": "Important outcome of effective legal and economic systems",
                },
            ]
        ],
        max_length=6,
        min_length=6,
    )


class SentenceFrame(BaseModel):
    proficiency_level: ProficiencyLevel = Field(
        ..., description="WIDA proficiency level group"
    )
    english: str = Field(
        ..., description="English sentence frame/stem/question", min_length=2
    )
    portuguese: str = Field(
        ..., description="Portuguese sentence frame/stem/question", min_length=2
    )
    language_function: str = Field(
        ...,
        description="Target language function (e.g., explain, compare, describe, argue)",
        examples=["explain", "compare", "describe", "argue", "sequence", "justify"],
    )
    frame_type: FrameType = Field(
        ...,
        description="Type of frame: frame for Levels 1-2/3-4, stem or open_question for Levels 5-6",
    )


class SentenceFrames(RootModel[list[SentenceFrame]]):
    root: list[SentenceFrame] = Field(
        ...,
        description="List of exactly 8 sentence frames/stems/questions distributed by WIDA proficiency levels: 3 for Levels 1-2, 3 for Levels 3-4, and 2 for Levels 5-6 (1 stem + 1 open question)",
        examples=[
            [
                {
                    "proficiency_level": "levels_1_2",
                    "english": "This is ___",
                    "portuguese": "Isto é ___",
                    "language_function": "identify",
                    "frame_type": "frame",
                },
                {
                    "proficiency_level": "levels_1_2",
                    "english": "I see ___",
                    "portuguese": "Eu vejo ___",
                    "language_function": "describe",
                    "frame_type": "frame",
                },
                {
                    "proficiency_level": "levels_1_2",
                    "english": "It has ___",
                    "portuguese": "Tem ___",
                    "language_function": "describe",
                    "frame_type": "frame",
                },
                {
                    "proficiency_level": "levels_3_4",
                    "english": "First ___, then ___",
                    "portuguese": "Primeiro ___, depois ___",
                    "language_function": "sequence",
                    "frame_type": "frame",
                },
                {
                    "proficiency_level": "levels_3_4",
                    "english": "This shows ___ because ___",
                    "portuguese": "Isso mostra ___ porque ___",
                    "language_function": "explain",
                    "frame_type": "frame",
                },
                {
                    "proficiency_level": "levels_3_4",
                    "english": "I think ___ because ___",
                    "portuguese": "Eu acho ___ porque ___",
                    "language_function": "justify",
                    "frame_type": "frame",
                },
                {
                    "proficiency_level": "levels_5_6",
                    "english": "Evidence suggests that ___",
                    "portuguese": "As evidências sugerem que ___",
                    "language_function": "argue",
                    "frame_type": "stem",
                },
                {
                    "proficiency_level": "levels_5_6",
                    "english": "How does ___ relate to ___?",
                    "portuguese": "Como ___ se relaciona com ___?",
                    "language_function": "analyze",
                    "frame_type": "open_question",
                },
            ]
        ],
        max_length=8,
        min_length=8,
    )


class Homework(BaseModel):
    original_content: str = Field(
        ...,
        description="Original homework from primary teacher (may be empty)",
        examples=["", "Read pages 45-50", "Complete worksheet"],
    )
    family_connection: str = Field(
        ...,
        description="Family-friendly Portuguese-English home activity",
        examples=[
            "Ask family: 'Como as leis ajudam nossa comunidade?' (How do laws help our community?) Discuss in Portuguese/English and share one example in class."
        ],
        min_length=30,
    )


class CoTeachingModel(BaseModel):
    model_name: ModelName = Field(
        ..., description="Friend & Cook co-teaching model name"
    )

    @field_validator("model_name", mode="before")
    @classmethod
    def normalize_model_name(cls, v: str | ModelName) -> ModelName:
        """Map short/lowercase LLM values to full ModelName enum (e.g. 'station' -> Station Teaching)."""
        if isinstance(v, ModelName):
            return v
        s = (v or "").strip().lower()
        mapping = {
            "station": ModelName.Station_Teaching,
            "parallel": ModelName.Parallel_Teaching,
            "team": ModelName.Team_Teaching,
            "alternative": ModelName.Alternative_Teaching,
            "one teach one assist": ModelName.One_Teach_One_Assist,
            "one assist": ModelName.One_Teach_One_Assist,
            "one teach one observe": ModelName.One_Teach_One_Observe,
            "one observe": ModelName.One_Teach_One_Observe,
        }
        if s in mapping:
            return mapping[s]
        try:
            return ModelName(v)
        except ValueError:
            return ModelName(v.strip())

    rationale: str = Field(
        ...,
        description="WIDA band-based reasoning for model selection",
        examples=[
            "Mixed range (4+ levels) needs differentiated stations or dual support"
        ],
        min_length=20,
    )
    wida_context: str = Field(
        ...,
        description="WIDA proficiency distribution description",
        examples=[
            "Mixed range with typical 7th grade distribution (Levels 2-5), requiring differentiated small-group support for complex historical content"
        ],
        min_length=30,
    )
    phase_plan: list[Phase] = Field(
        ...,
        description="45-minute phase breakdown with teacher roles",
        max_length=4,
        min_length=2,
    )
    implementation_notes: list[ImplementationNote] = Field(
        ...,
        description="Key coordination points, materials, and transitions",
        min_length=1,
    )
    warnings: list[str] = Field(
        ..., description="Optional warnings about constraints or issues"
    )


class Misconceptions(BaseModel):
    original_content: str = Field(
        ...,
        description="Original content misconception from primary teacher",
        examples=["Students may believe there is no correlation between trade and law"],
    )
    linguistic_note: LinguisticNote


class Assessment(BaseModel):
    primary_assessment: str = Field(
        ...,
        description="Original assessment from primary teacher (verbatim)",
        examples=["Exit Ticket", "Quiz on Roman systems", "Presentation"],
        min_length=5,
    )
    bilingual_overlay: BilingualOverlay


class TailoredInstruction(BaseModel):
    original_content: str = Field(
        ..., description="Original tailored instruction from primary teacher"
    )
    co_teaching_model: CoTeachingModel
    ell_support: list[EllStrategy] = Field(
        ...,
        description="3-5 bilingual strategies with implementation details",
        max_length=5,
        min_length=3,
    )
    special_needs_support: list[SpecialNeedsSupportItem] = Field(
        ..., description="1-2 simple accommodations", max_length=2, min_length=1
    )
    materials: list[Material] = Field(
        ..., description="Concrete, low-prep materials list"
    )


class DayPlanSingleSlot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unit_lesson: str = Field(
        ...,
        description="Unit, Lesson number, and Module identifier",
        examples=["Unit One Lesson Seven", "Module 3 Lesson 12"],
    )
    objective: Objective | None = None
    anticipatory_set: AnticipatorySet | None = None
    vocabulary_cognates: VocabularyCognates | None = None
    sentence_frames: SentenceFrames | None = None
    tailored_instruction: TailoredInstruction | None = None
    misconceptions: Misconceptions | None = None
    assessment: Assessment | None = None
    homework: Homework | None = None


class SlotPlan(BaseModel):
    slot_number: int = Field(..., description="Slot number (1, 2, 3, etc.)", ge=1)
    subject: str | None = Field(
        None,
        description="Subject for this slot",
        examples=["ELA", "Math", "Science", "Social Studies"],
    )
    unit_lesson: str = Field(
        ...,
        description="Unit, Lesson number, and Module identifier",
        examples=["Unit One Lesson Seven", "Module 3 Lesson 12"],
    )
    objective: Objective | None = None
    anticipatory_set: AnticipatorySet | None = None
    vocabulary_cognates: VocabularyCognates | None = None
    sentence_frames: SentenceFrames | None = None
    tailored_instruction: TailoredInstruction | None = None
    misconceptions: Misconceptions | None = None
    assessment: Assessment | None = None
    homework: Homework | None = None


# DEPRECATED: DayPlanMultiSlot is not used in DayPlan union type for AI generation
# Kept for backward compatibility with merged lesson data created by tools/json_merger.py
# IMPORTANT: AI should NEVER generate DayPlanMultiSlot structures - only DayPlanSingleSlot
# Multi-slot structures are created by merging multiple single-slot lessons, not by AI
class DayPlanMultiSlot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slots: list[SlotPlan] = Field(
        ...,
        description="Array of slot-specific lesson plans for this day",
        min_length=1,
    )


# IMPORTANT: This schema only allows single-slot structures for AI generation.
# This eliminates schema ambiguity that caused AI confusion between structures.
#
# Multi-slot structures (DayPlanMultiSlot) are created by merging multiple
# single-slot lessons using tools/json_merger.py, NOT by AI generation.
#
# The AI should ALWAYS generate DayPlanSingleSlot structures only.
# Code that handles multi-slot (PDF generators, etc.) is for processing merged data.
class DayPlan(RootModel[DayPlanSingleSlot]):
    root: DayPlanSingleSlot


class Days(BaseModel):
    monday: DayPlan | None = None
    tuesday: DayPlan | None = None
    wednesday: DayPlan | None = None
    thursday: DayPlan | None = None
    friday: DayPlan | None = None


class BilingualLessonPlanOutputSchema(BaseModel):
    metadata: Metadata = Field(
        ..., description="Lesson plan metadata and identification"
    )
    days: Days = Field(..., description="Lesson plans for each day of the week")
