# generated by datamodel-codegen:
#   filename:  lesson_output_schema.json
#   timestamp: 2025-12-28T19:42:11+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, RootModel, field_validator

from backend.lesson_schema_enums import ModelName, PatternId
from backend.lesson_schema_support import BilingualOverlay, SupportsByLevel
from backend.lesson_schema_vocabulary import (
    Homework,
    SentenceFrame,
    SentenceFrames,
    VocabularyCognate,
    VocabularyCognates,
)


class Metadata(BaseModel):
    week_of: str = Field(
        ...,
        description="Week date range (MM/DD-MM/DD)",
        examples=["10/6-10/10", "3/15-3/19"],
        pattern="^\\d{1,2}/\\d{1,2}-\\d{1,2}/\\d{1,2}$",
    )
    grade: str = Field(
        ..., description="Grade level", examples=["K", "1", "2", "7", "12"]
    )
    subject: str = Field(
        ...,
        description="Subject area",
        examples=["Social Studies", "Math", "Language Arts", "Science"],
    )
    homeroom: str = Field(
        ...,
        description="Homeroom or class identifier",
        examples=["302", "Room 15", "Class A"],
    )
    room: str | None = Field(
        None,
        description="Room number or physical location where instruction takes place",
        examples=["215", "302", "Science Lab A", "Building B, Room 15"],
    )
    teacher_name: str = Field(..., description="Primary teacher name")


class Objective(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    content_objective: str = Field(
        ...,
        description="Original content objective from primary teacher",
        examples=[
            "Students will be able to explain how systems of law and banking enabled growth in trade, wealth, and peace"
        ],
        min_length=10,
    )
    student_goal: str = Field(
        ...,
        description="Student-friendly 'I will...' version (max 12 words for board posting) that explicitly names the WIDA language domains (listening, reading, speaking, writing) students will practice and ends with a parentheses domain tag followed by a period (e.g., '(listening, speaking).')",
        examples=[
            "I will explain Roman systems using evidence and speak with my team (speaking).",
            "I will read the article, discuss it, and write a summary (reading, speaking, writing).",
        ],
        max_length=120,
        min_length=5,
        pattern="^(?=.*\\b(?:[Ll]isten(?:ing)?|[Rr]ead(?:ing)?|[Ss]peak(?:ing)?|[Ww]rit(?:e|ing))\\b).*\\((?: *(?:listening|reading|speaking|writing))(?: *, *(?:listening|reading|speaking|writing))* *\\)\\.$",
    )
    wida_objective: str = Field(
        ...,
        description="Complete WIDA bilingual language objective with ELD standard",
        examples=[
            "Students will use language to explain how Roman law, banking, and Pax Romana enabled economic growth (ELD-SS.6-8.Explain.Reading/Writing) by using cognate awareness and graphic organizers with Portuguese-English vocabulary bridges appropriate for WIDA levels 2-5, producing a written explanation that demonstrates understanding of cause-effect relationships in historical systems."
        ],
        min_length=50,
        pattern=".*ELD-[A-Z]{2}\\.[0-9K-]+\\.[A-Za-z]+\\.(?:Listening|Reading|Speaking|Writing)(?:/(?:Listening|Reading|Speaking|Writing))*.*",
    )


class AnticipatorySet(BaseModel):
    original_content: str = Field(
        ...,
        description="Original anticipatory set from primary teacher",
        examples=["Students will respond to an everybody writes."],
    )
    bilingual_bridge: str = Field(
        ...,
        description="1-2 concrete steps to connect L1/culture to lesson entry",
        examples=[
            "Preview key Portuguese-English vocabulary pairs: **law** → *lei*, **banking** → *banco*, **trade** → *comércio*, **peace** → *paz*. Quick L1 connection: 'Como as leis ajudam o comércio?' (How do laws help trade?)"
        ],
        min_length=20,
    )


class SpecialNeedsSupportItem(RootModel[str]):
    root: str = Field(
        ...,
        examples=[
            "Visual timeline of Roman systems; color-code law (blue), banking (green), Pax Romana (gold)"
        ],
        min_length=10,
    )


class Material(RootModel[str]):
    root: str = Field(
        ...,
        examples=[
            "Bilingual vocabulary chart (poster paper)",
            "Cornell Notes template (handout)",
            "Sentence frame strips",
        ],
        min_length=5,
    )


class ImplementationNote(RootModel[str]):
    root: str = Field(
        ...,
        examples=["Prepare 3 station signs, rotation chart, visual timer"],
        min_length=10,
    )


class Phase(BaseModel):
    phase_name: str = Field(
        ...,
        description="Phase name (Warmup, Input, Practice, Closure, etc.)",
        examples=["Warmup", "Practice", "Closure", "Input"],
        min_length=3,
    )
    minutes: int = Field(..., description="Duration in minutes", ge=1, le=45)
    bilingual_teacher_role: str = Field(
        ...,
        description="Bilingual teacher's role during this phase",
        examples=["Station 1: Intensive vocabulary/L1 cognate work with Levels 2-3"],
        min_length=10,
    )
    primary_teacher_role: str = Field(
        ...,
        description="Primary teacher's role during this phase",
        examples=["Station 2: Content application with Levels 4-5"],
        min_length=10,
    )
    details: str = Field(
        "",
        description="Additional phase details (optional)",
        examples=[
            "Station 3 (Independent): Bilingual materials practice (all levels rotate). Rotation: 10 minutes per station with visual timer"
        ],
    )


class EllStrategy(BaseModel):
    strategy_id: str = Field(
        ...,
        description="Strategy identifier from strategy pack",
        examples=["cognate_awareness", "graphic_organizers", "sentence_frames"],
        pattern="^[a-z_]+$",
    )
    strategy_name: str = Field(
        ...,
        description="Human-readable strategy name",
        examples=["Cognate Awareness", "Graphic Organizers", "Sentence Frames"],
        min_length=5,
    )
    implementation: str = Field(
        ...,
        description="Specific implementation steps for this lesson",
        examples=[
            "Create bilingual vocabulary anchor chart with Portuguese-English pairs: **law** → *lei*, **system** → *sistema*, **economy** → *economia*, **empire** → *império*. Post visibly during slideshow."
        ],
        min_length=30,
    )
    proficiency_levels: str = Field(
        ...,
        description="Target WIDA proficiency levels",
        examples=["Levels 2-5", "Levels 2-3", "Level 1", "Levels 3-4"],
        pattern="^Levels? [0-9](-[0-9])?(, [0-9](-[0-9])?)*$",
    )


class LinguisticNote(BaseModel):
    pattern_id: PatternId = Field(
        ..., description="Pattern identifier from portuguese_misconceptions.json"
    )
    note: str = Field(
        ...,
        description="Explanation of L1→L2 interference",
        examples=[
            "Portuguese speakers often drop subject pronouns ('Go to school' instead of 'I go to school') because verb conjugation shows the person"
        ],
        min_length=30,
    )
    prevention_tip: str = Field(
        ...,
        description="Actionable prevention strategy",
        examples=[
            "Use sentence frames that explicitly include subject pronouns: 'I [verb]...', 'She [verb]...', 'They [verb]...'"
        ],
        min_length=20,
    )


class CoTeachingModel(BaseModel):
    model_name: ModelName = Field(
        ..., description="Friend & Cook co-teaching model name"
    )

    @field_validator("model_name", mode="before")
    @classmethod
    def normalize_model_name(cls, v: str | ModelName) -> ModelName:
        """Map short/lowercase LLM values to full ModelName enum (e.g. 'station' -> Station Teaching)."""
        if isinstance(v, ModelName):
            return v
        s = (v or "").strip().lower()
        mapping = {
            "station": ModelName.Station_Teaching,
            "parallel": ModelName.Parallel_Teaching,
            "team": ModelName.Team_Teaching,
            "alternative": ModelName.Alternative_Teaching,
            "one teach one assist": ModelName.One_Teach_One_Assist,
            "one assist": ModelName.One_Teach_One_Assist,
            "one teach one observe": ModelName.One_Teach_One_Observe,
            "one observe": ModelName.One_Teach_One_Observe,
        }
        if s in mapping:
            return mapping[s]
        try:
            return ModelName(v)
        except ValueError:
            return ModelName(v.strip())

    rationale: str = Field(
        ...,
        description="WIDA band-based reasoning for model selection",
        examples=[
            "Mixed range (4+ levels) needs differentiated stations or dual support"
        ],
        min_length=20,
    )
    wida_context: str = Field(
        ...,
        description="WIDA proficiency distribution description",
        examples=[
            "Mixed range with typical 7th grade distribution (Levels 2-5), requiring differentiated small-group support for complex historical content"
        ],
        min_length=30,
    )
    phase_plan: list[Phase] = Field(
        ...,
        description="45-minute phase breakdown with teacher roles",
        max_length=4,
        min_length=2,
    )
    implementation_notes: list[ImplementationNote] = Field(
        ...,
        description="Key coordination points, materials, and transitions",
        min_length=1,
    )
    warnings: list[str] = Field(
        ..., description="Optional warnings about constraints or issues"
    )


class Misconceptions(BaseModel):
    original_content: str = Field(
        ...,
        description="Original content misconception from primary teacher",
        examples=["Students may believe there is no correlation between trade and law"],
    )
    linguistic_note: LinguisticNote


class Assessment(BaseModel):
    primary_assessment: str = Field(
        ...,
        description="Original assessment from primary teacher (verbatim)",
        examples=["Exit Ticket", "Quiz on Roman systems", "Presentation"],
        min_length=5,
    )
    bilingual_overlay: BilingualOverlay


class TailoredInstruction(BaseModel):
    original_content: str = Field(
        ..., description="Original tailored instruction from primary teacher"
    )
    co_teaching_model: CoTeachingModel
    ell_support: list[EllStrategy] = Field(
        ...,
        description="3-5 bilingual strategies with implementation details",
        max_length=5,
        min_length=3,
    )
    special_needs_support: list[SpecialNeedsSupportItem] = Field(
        ..., description="1-2 simple accommodations", max_length=2, min_length=1
    )
    materials: list[Material] = Field(
        ..., description="Concrete, low-prep materials list"
    )


class DayPlanSingleSlot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unit_lesson: str = Field(
        ...,
        description="Unit, Lesson number, and Module identifier",
        examples=["Unit One Lesson Seven", "Module 3 Lesson 12"],
    )
    objective: Objective | None = None
    anticipatory_set: AnticipatorySet | None = None
    vocabulary_cognates: VocabularyCognates | None = None
    sentence_frames: SentenceFrames | None = None
    tailored_instruction: TailoredInstruction | None = None
    misconceptions: Misconceptions | None = None
    assessment: Assessment | None = None
    homework: Homework | None = None


class SlotPlan(BaseModel):
    slot_number: int = Field(..., description="Slot number (1, 2, 3, etc.)", ge=1)
    subject: str | None = Field(
        None,
        description="Subject for this slot",
        examples=["ELA", "Math", "Science", "Social Studies"],
    )
    unit_lesson: str = Field(
        ...,
        description="Unit, Lesson number, and Module identifier",
        examples=["Unit One Lesson Seven", "Module 3 Lesson 12"],
    )
    objective: Objective | None = None
    anticipatory_set: AnticipatorySet | None = None
    vocabulary_cognates: VocabularyCognates | None = None
    sentence_frames: SentenceFrames | None = None
    tailored_instruction: TailoredInstruction | None = None
    misconceptions: Misconceptions | None = None
    assessment: Assessment | None = None
    homework: Homework | None = None


# DEPRECATED: DayPlanMultiSlot is not used in DayPlan union type for AI generation
# Kept for backward compatibility with merged lesson data created by tools/json_merger.py
# IMPORTANT: AI should NEVER generate DayPlanMultiSlot structures - only DayPlanSingleSlot
# Multi-slot structures are created by merging multiple single-slot lessons, not by AI
class DayPlanMultiSlot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slots: list[SlotPlan] = Field(
        ...,
        description="Array of slot-specific lesson plans for this day",
        min_length=1,
    )


# IMPORTANT: This schema only allows single-slot structures for AI generation.
# This eliminates schema ambiguity that caused AI confusion between structures.
#
# Multi-slot structures (DayPlanMultiSlot) are created by merging multiple
# single-slot lessons using tools/json_merger.py, NOT by AI generation.
#
# The AI should ALWAYS generate DayPlanSingleSlot structures only.
# Code that handles multi-slot (PDF generators, etc.) is for processing merged data.
class DayPlan(RootModel[DayPlanSingleSlot]):
    root: DayPlanSingleSlot


class Days(BaseModel):
    monday: DayPlan | None = None
    tuesday: DayPlan | None = None
    wednesday: DayPlan | None = None
    thursday: DayPlan | None = None
    friday: DayPlan | None = None


class BilingualLessonPlanOutputSchema(BaseModel):
    metadata: Metadata = Field(
        ..., description="Lesson plan metadata and identification"
    )
    days: Days = Field(..., description="Lesson plans for each day of the week")
